import { useState } from 'react'

export function usePDFReport() {
  const [downloading, setDownloading] = useState(false)
  const [lastReport, setLastReport] = useState(null)

  const download = async (scanId, targetName = 'RAG System') => {
    if (!scanId) return
    setDownloading(true)
    try {
      const res = await fetch(`/api/v1/report/${scanId}`)
      if (res.ok) {
        const blob = await res.blob()
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `corpusguard_report_${scanId}.pdf`
        a.click()
        URL.revokeObjectURL(url)
        setLastReport({ scanId, downloadedAt: new Date().toLocaleTimeString() })
      } else {
        generateClientPDF(scanId, targetName)
      }
    } catch {
      generateClientPDF(scanId, targetName)
    } finally {
      setDownloading(false)
    }
  }

  return { download, downloading, lastReport }
}

function generateClientPDF(scanId, targetName) {
  const content = `CorpusGuard Security Report\n${'='.repeat(50)}\nScan ID: ${scanId}\nTarget: ${targetName}\nGenerated: ${new Date().toISOString()}\n\nThis report was generated by CorpusGuard v0.2.0\nBased on SSRN 6734225 — Frankline Ondieki Ombachi\nhttps://github.com/OndiekiFrank/CorpusGuard`
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `corpusguard_report_${scanId}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export function PDFButton({ scanId, targetName, downloading, onDownload }) {
  if (!scanId) return (
    <button disabled style={{ height: 36, padding: '0 16px', background: 'var(--bg2)', color: 'var(--text-muted)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 8 }}>
      📄 PDF report
    </button>
  )

  return (
    <button
      onClick={() => onDownload(scanId, targetName)}
      disabled={downloading}
      style={{ height: 36, padding: '0 16px', background: 'var(--purple-bg)', color: 'var(--purple)', border: '1px solid rgba(128,90,213,0.3)', display: 'flex', alignItems: 'center', gap: 8 }}
    >
      {downloading ? <><Spin /> Generating...</> : <>📄 Download PDF</>}
    </button>
  )
}

function Spin() {
  return <span style={{ width: 12, height: 12, border: '2px solid rgba(128,90,213,0.3)', borderTopColor: 'var(--purple)', borderRadius: '50%', display: 'inline-block', animation: 'spin 0.7s linear infinite' }} />
}
